behaviors:
  gewu:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple

    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0

    keep_checkpoints: 5
    max_steps: 3.0e7
    time_horizon: 128
    summary_freq: 10000



environment_parameters:
  lesson:
    curriculum:
      - name: lesson0
        completion_criteria:
          measure: reward
          behavior: gewu
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 2000
        value: 0
      - name: lesson1
        completion_criteria:
          measure: reward
          behavior: gewu
          signal_smoothing: true
          min_lesson_length: 150
          threshold: 2000
        value: 1
      - name: lesson2
        completion_criteria:
          measure: reward
          behavior: gewu
          signal_smoothing: true
          min_lesson_length: 150
          threshold: 2000
        value: 2
      - name: lesson3
        completion_criteria:
          measure: reward
          behavior: gewu
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 2000
        value: 3
      - name: lesson4
        completion_criteria:
          measure: reward
          behavior: gewu
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 2000
        value: 4
      - name: lesson5
        completion_criteria:
          measure: reward
          behavior: gewu
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 2000
        value: 5
      - name: lesson6
        completion_criteria:
          measure: reward
          behavior: gewu
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 2000
        value: 6
      - name: lesson7
        completion_criteria:
          measure: reward
          behavior: gewu
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 2000
        value: 7
